# Generated by Django 4.2.16 on 2025-01-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_product_is_featured"),
        ("orders", "0002_alter_order_total_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipments",
            fields=[
                ("shipping_id", models.AutoField(primary_key=True, serialize=False)),
                ("card_transaction_time", models.DateTimeField()),
                ("packing_time", models.DateTimeField()),
                ("shipping_order_time", models.DateTimeField()),
                (
                    "order_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
        ),
    ]
