# Generated by Django 4.2.16 on 2025-02-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("apple_pay", "Apple Pay"),
                    ("visa", "Visa"),
                    ("mastercard", "Mastercard"),
                    ("amex", "American Express"),
                    ("klarna", "Klarna"),
                ],
                default="visa",
                max_length=30,
            ),
        ),
    ]
